### ISSUE TITLE
directing output into next available row

### ISSUE THREAD

**Issue by jshoyes** [davisjp1822/enbc2csv#1]
This is a great tool you created here. It works on my end, however the outputs seem to replace one another in the csv file instead of going into the next available row. If it's not already present, would it be possible to add this feature?

**Comment by davisjp1822** [comment]
Hi Shaun - thanks for the feedback and for using the tool. 

I just tested on my end, and it looks like the tool is appending to the CSV file just fine. My process is as follows:
1. Select a group of business cards in Evernote, right click, and select "Export Notes". In this case, I exported the notes to Desktop/My Notes and made sure they were all saved in HTML format.
2. From the terminal, I executed the following command:

python enbc2csv.py -i ~/Desktop/My\ Notes/*.html -o foo.csv

The *.html selects all of the files in the "My Notes" directory.

foo.csv has all of the entries, as expected.

Could you paste what commands you are using please?

**Comment by jshoyes** [comment]
Yikes - I was missing the `*` in `*.html`. It works fine for me now. I appreciate your quick response. Thanks!

**Comment by davisjp1822** [comment]
Glad I could help!

**Comment by davisjp1822** [comment]
My pleasure! Thanks for using the tool.
